name: CAD Compare

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Perl Comparison
        run: |
          perl compare2.pl \
            --golden=golden \
            --result=result \
            --fields=Voltage\
            --output=compare_report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: comparison-report
          path: compare_report.txt