name: CAD Compare

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Perl Comparison
        run: |
          perl compare2.pl \
            --golden=golden \
            --result=result \
            --fields=Voltage,Delay,Power \
            --output=compare_report.txt

      - name: Upload Report
        uses: actions/upload-artifact@ee0669bd1cc54295c223e0bb666b733df41de1c5
        with:
          name: comparison-report
          path: compare_report.txt